/*******************************************************************************
* File Name: cyfitter_sysint.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_SYSINT_H
#define INCLUDED_CYFITTER_SYSINT_H
#include "cy_device_headers.h"

/* UART_SCB_IRQ */
#define UART_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define UART_SCB_IRQ__INTC_CORTEXM0P_MUX 10u
#define UART_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define UART_SCB_IRQ__INTC_NUMBER 46u
#define UART_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define UART_SCB_IRQ_INTC_CORTEXM0P_MUX 10u
#define UART_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define UART_SCB_IRQ_INTC_NUMBER 46u

/* Timer_Echo_Int */
#define Timer_Echo_Int__INTC_CORTEXM0P_ASSIGNED 1
#define Timer_Echo_Int__INTC_CORTEXM0P_MUX 8u
#define Timer_Echo_Int__INTC_CORTEXM0P_PRIORITY 3u
#define Timer_Echo_Int__INTC_NUMBER 90u
#define Timer_Echo_Int_INTC_CORTEXM0P_ASSIGNED 1
#define Timer_Echo_Int_INTC_CORTEXM0P_MUX 8u
#define Timer_Echo_Int_INTC_CORTEXM0P_PRIORITY 3u
#define Timer_Echo_Int_INTC_NUMBER 90u

/* SensorBus_SCB_IRQ */
#define SensorBus_SCB_IRQ__INTC_CORTEXM0P_ASSIGNED 1
#define SensorBus_SCB_IRQ__INTC_CORTEXM0P_MUX 9u
#define SensorBus_SCB_IRQ__INTC_CORTEXM0P_PRIORITY 3u
#define SensorBus_SCB_IRQ__INTC_NUMBER 47u
#define SensorBus_SCB_IRQ_INTC_CORTEXM0P_ASSIGNED 1
#define SensorBus_SCB_IRQ_INTC_CORTEXM0P_MUX 9u
#define SensorBus_SCB_IRQ_INTC_CORTEXM0P_PRIORITY 3u
#define SensorBus_SCB_IRQ_INTC_NUMBER 47u

#endif /* INCLUDED_CYFITTER_SYSINT_H */
